---
apiVersion: v1
kind: Secret
metadata:
  name: plausible
  namespace: default
type: Opaque
stringData:
  SECRET_KEY_BASE: <todo:replaceme>     # a randomly generated string. the longer the better
  ADMIN_USER_NAME: admin                # your login user name
  ADMIN_USER_EMAIL: <todo:replaceme>    # your login email
  ADMIN_USER_PWD: <todo:replaceme>      # 100% up to you
  
  # see postgres.yaml for setting the database password
  DATABASE_URL: postgres://postgres:<todo:replaceme>@postgres-service.svc.cluster.local:5432/postgres
  CLICKHOUSE_DATABASE_URL: http://clickhouse-service.svc.cluster.local:8123/plausible
  BASE_URL: https://<todo:replaceme>    # same address you used in ingress.yaml
  MAILER_EMAIL: <todo:replaceme>        # email@example.com
  SMTP_HOST_ADDR: <todo:replaceme>      # smtp.example.com
  SMTP_HOST_PORT: "465"
  SMTP_HOST_SSL_ENABLED: "true"
  SMTP_USER_NAME: <todo:replaceme>      # email@example.com
  SMTP_USER_PWD: <todo:replaceme>
  DISABLE_REGISTRATION: "true"
